### ISSUE TITLE
Syntax error returned if updating to plugin version 1.0.4 when using php 7.2

### ISSUE THREAD

**Issue by paulgoodfield** [codewithkyle/craft-readonly#4]
### Description

Syntax error returned if updating to plugin version 1.0.4 when using php 7.2. Exact error is:

`syntax error, unexpected '|', expecting ';' or '{'`

The line it references is `public function getContentColumnType(): array|string` (line 75 in `/app/craft/vendor/codewithkyle/read-only/src/fields/ReadOnlyField.php`).

Looks like this is an issue with trying to use union types when type hinting the return value from that method. That is only supported in php 8.0 onwards I believe, but version 1.0.4 of this plugin states that it can be used with php 7.2 in the composer.json platform config. Have had to roll back to version 1.0.1.

### Steps to reproduce

1. On a Craft 3.x site using php 7.2, update plugin to use version 1.0.4 (updating from version 1.0.1 in my case)
2. After plugin updated, loading any page on front or back-end of site results in 500 syntax error

### Additional info

- Craft version: 3.7.63.1
- PHP version: 7.2.34
- Database driver & version:  MySQL 5.5.5
- Plugins & versions:

AsyncQueue	2.3.0
Category Groups Field	1.3.0
Colour Swatches	1.7.0
Cookies	1.1.15
Craft Commerce	3.4.19
Disqus	1.1.3
Element API	2.8.6.1
Environment Label	3.2.0
Events	1.4.24
Freeform	3.13.22.1
Navigation	1.4.31
oEmbed	1.13.19
PDF Transform	1.0.9
Read Only	1.0.1
Reasons	2.3.1
Redactor	2.10.11
Redirect Manager	1.1.1
Section Field	1.1.0
SEOmatic	3.4.36
Stripe for Craft Commerce	2.4.3
Super Table	2.7.2
Tags	1.0.9
User Group Field	1.0.4

**Comment by codewithkyle** [comment]
Look like I screwed up adding the Craft 4 & PHP 8 support in v1.0.3 and v1.0.4. I've deleted both of those version from Packagist. v1.0.2 should be the latest version for Craft 3 with PHP 7 and v1.0.5 will require Craft 4 and PHP 8.

**Comment by paulgoodfield** [comment]
@codewithkyle great - thanks for the speedy response!

**Comment by codewithkyle** [comment]
I believe this issue has been resolved so I will be closing this issue. If it persist or reoccurs reopen it and I will continue to look for a new solution.
